#spotnow.pubs
version: '3.3'
services:
  srvpubs:
    #depends_on:
      #- reverseproxy
    image: srvpubs
    container_name: srvpubs
    build:
      context: .
      dockerfile: dockerfile
    #expose:       
      # Opens port on the container
    #  - '8888'
    ports:
      - "8888:8888"
    restart: always
    command: "python3 publisher.py runserver 0.0.0.0:8888"
    
