# Generated by Django 2.2.4 on 2019-12-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191209_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='isinactive',
            field=models.IntegerField(blank=True, db_column='isInactive', null=True),
        ),
    ]
