# Generated by Django 2.2.4 on 2019-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191209_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartlock',
            name='isinactive',
            field=models.BooleanField(blank=True, db_column='IsInactive', null=True),
        ),
    ]
