# Generated by Django 2.2.4 on 2019-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191210_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updateddate',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='updateddate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactiontype_id',
        ),
        migrations.AddField(
            model_name='garage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='garage',
            name='preço',
            field=models.CharField(db_column='Preço', default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', null=True),
        ),
    ]
