# Generated by Django 2.2.4 on 2019-12-10 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191210_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'comentario',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='preço',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='borkermargin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='isinactive',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updateddate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='valueclosed',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='updateddate',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='updateddate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='isinactive',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updateddate',
        ),
        migrations.AddField(
            model_name='booking',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Comentario'),
        ),
    ]
