# Generated by Django 2.2.4 on 2019-12-18 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191210_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='booking',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Booking'),
            preserve_default=False,
        ),
    ]
