# Generated by Django 2.2.4 on 2019-12-18 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191218_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
