# Generated by Django 2.2.4 on 2019-12-18 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191218_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartlock',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
