# Generated by Django 2.2.4 on 2020-01-15 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_client_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
