# Official Python runtime as a parent image
FROM python:3.7-alpine
# Set environment variables
# Python won’t try to write .pyc files which we do not want.
ENV PYTHONDONTWRITEBYTECODE 1
# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED 1
# create root directory for our project in the container
RUN mkdir /spotnow.raspi
# Set the working directory 
WORKDIR /spotnow.raspi
# Copy the current directory contents into the container 
ADD . /spotnow.raspi
EXPOSE 8880

#RUN pip3 install --no-cache-dir -r requirements.txt
#RUN pip install -r requirements.txt




RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev 
    #&& apk add --no-cache mariadb-dev

#RUN pip3 install --no-cache-dir -r requirements.txt

#RUN pip3 install mysqlclient  

RUN apk --update add \
    build-base \
    jpeg-dev \
    zlib-dev

#RUN pip3 install Pillow 

RUN apk del build-deps

RUN pip install kubemq

#CMD python ./subscriber.py
